# Template for preview environments
image:
  repository: acrvclusterpoc.azurecr.io/task-manager
  tag: "6b10587b04653ffb90093fce7be9ec3ef2b748b1"
  pullPolicy: Always

replicaCount: 1

ingress:
  enabled: true
  className: nginx
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
  hosts:
    - host: feature-341-task-manager.bahram.az
      paths:
        - path: /
          pathType: Prefix

resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 50m
    memory: 64Mi

env:
  APP_ENV: preview

service:
  type: ClusterIP
  port: 80