apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: my-app-production

resources:
- ../base

namespace: production

commonLabels:
  app: my-app
  environment: production
  version: v1.0.0

commonAnnotations:
  managed-by: kustomize
  environment: production
  contact: devops@example.com

patchesStrategicMerge:
- deployment-patch.yaml

patchesJson6902:
- target:
    group: apps
    version: v1
    kind: Deployment
    name: my-app
  patch: |-
    - op: replace
      path: /spec/replicas
      value: 5
    - op: replace
      path: /spec/template/spec/containers/0/env/0/value
      value: "production"

images:
- name: my-app
  newName: my-app
  newTag: v1.0.0-prod

configMapGenerator:
- name: app-config
  literals:
  - ENVIRONMENT=production
  - LOG_LEVEL=info
  - DEBUG=false

secretGenerator:
- name: app-secrets
  literals:
  - DATABASE_URL=postgresql://prod-db:5432/myapp
  - API_KEY=prod-api-key-12345
