image:
  repository: acrvclusterpoc.azurecr.io/task-manager
  tag: "49fb54cf531a5cd1d811ea3637f5c101c17afcce"
  pullPolicy: IfNotPresent

replicaCount: 1

env:
  APP_ENV: "{{- include "task-manager.labels" . | nindent 4 }}"
  APP_MESSAGE: "Hello from task-manager!"

service:
  type: ClusterIP
  port: 80
  targetPort: 8000

ingress:
  enabled: true
  className: nginx
  host: feature-123-task-manager.bahram.az
  tlsEnabled: false
  tls: []

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 512Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 80
